version: "3.9"

services:
  apiserver:
    build: .
    container_name: apiserver
    networks:
      - rabbit_network
    ports:
       - "1337:1337"
    environment:
        RABBITMQ_HOST: rabbitmq    

networks:
  rabbit_network:
    external: true
    driver: bridge